name: book_nexsus
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11

  

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: NB
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf

    - family: NM
      fonts:
        - asset: assets/fonts/NotoSans-Medium.ttf

    - family: NR
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf